# TraefikManager.StaticConfig.psm1
# Static configuration generation and management for Traefik Manager

#Requires -Version 5.1
Set-StrictMode -Version Latest

# --- Static Configuration Generation ---
function New-TraefikStaticYaml {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Email,
        
        [Parameter(Mandatory = $true)]
        [string]$Domain,
        
        [Parameter(Mandatory = $true)]
        [ValidateSet("duckdns", "cloudflare")]
        [string]$DNSProvider,
        
        [Parameter(Mandatory = $true)]
        [string]$APIToken,
        
        [Parameter(Mandatory = $false)]
        [string]$CertResolver = "letsencrypt",
        
        [Parameter(Mandatory = $false)]
        [string]$ConfigDirectory = "/etc/traefik/conf.d"
    )

    $staticConfig = @"
# Static Traefik configuration
# Generated by Traefik Manager on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# --- Providers ---
providers:
  file:
    directory: $ConfigDirectory/
    watch: true

# --- EntryPoints ---
entryPoints:
  # Entrypoint for HTTP on port 80, which redirects to HTTPS
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  # Entrypoint for HTTPS on port 443
  websecure:
    address: ':443'
  # Entrypoint for the Traefik API and dashboard
  traefik:
    address: ':8080'

# --- Certificate Resolvers (Let's Encrypt) ---
certificatesResolvers:
  $CertResolver`:
    acme:
      email: "$Email"
      storage: /etc/traefik/ssl/acme.json
      dnsChallenge:
        provider: $DNSProvider
        delayBeforeCheck: 60
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# --- API & Dashboard ---
api:
  dashboard: true
  insecure: true

# --- Logging ---
log:
  filePath: /var/log/traefik/traefik.log
  format: json
  level: INFO

accessLog:
  filePath: /var/log/traefik/traefik-access.log
  format: json
  filters:
    statusCodes:
      - "400-599"
  bufferingSize: 100
  fields:
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
"@

    Write-TraefikLog "Generated static configuration for domain: $Domain with $DNSProvider provider" -Level "Success"
    return $staticConfig
}

# --- DNS Provider Credential Testing ---
function Test-DNSCredentials {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateSet("duckdns", "cloudflare")]
        [string]$Provider,
        
        [Parameter(Mandatory = $true)]
        [string]$Token,
        
        [Parameter(Mandatory = $false)]
        [string]$Domain = ""
    )

    try {
        switch ($Provider) {
            "duckdns" {
                return Test-DuckDNSCredentials -Token $Token -Domain $Domain
            }
            "cloudflare" {
                return Test-CloudflareCredentials -Token $Token
            }
        }
    }
    catch {
        Write-TraefikLog "Error testing $Provider credentials: $($_.Exception.Message)" -Level "Error"
        return $false
    }
}

function Test-DuckDNSCredentials {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Token,
        
        [Parameter(Mandatory = $true)]
        [string]$Domain
    )

    try {
        Write-TraefikLog "Testing Duck DNS credentials for domain: $Domain" -Level "Info"
        
        # Test with a dummy IP to validate token and domain
        $testUrl = "https://www.duckdns.org/update?domains=$Domain&token=$Token&ip=1.2.3.4&verbose=true"
        
        $response = Invoke-WebRequest -Uri $testUrl -TimeoutSec 10 -ErrorAction Stop
        $responseText = $response.Content
        
        if ($responseText -match "OK") {
            Write-TraefikLog "Duck DNS credentials validated successfully" -Level "Success"
            
            # Reset to clear the test IP
            $resetUrl = "https://www.duckdns.org/update?domains=$Domain&token=$Token&clear=true"
            Invoke-WebRequest -Uri $resetUrl -TimeoutSec 10 -ErrorAction SilentlyContinue | Out-Null
            
            return $true
        }
        else {
            Write-TraefikLog "Duck DNS validation failed: $responseText" -Level "Error"
            return $false
        }
    }
    catch {
        Write-TraefikLog "Duck DNS credential test failed: $($_.Exception.Message)" -Level "Error"
        return $false
    }
}

function Test-CloudflareCredentials {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Token
    )

    try {
        Write-TraefikLog "Testing Cloudflare API credentials" -Level "Info"
        
        $headers = @{
            "Authorization" = "Bearer $Token"
            "Content-Type" = "application/json"
        }
        
        $response = Invoke-WebRequest -Uri "https://api.cloudflare.com/client/v4/user/tokens/verify" -Headers $headers -TimeoutSec 10 -ErrorAction Stop
        $result = $response.Content | ConvertFrom-Json
        
        if ($result.success) {
            Write-TraefikLog "Cloudflare credentials validated successfully" -Level "Success"
            return $true
        }
        else {
            Write-TraefikLog "Cloudflare validation failed: $($result.errors -join ', ')" -Level "Error"
            return $false
        }
    }
    catch {
        Write-TraefikLog "Cloudflare credential test failed: $($_.Exception.Message)" -Level "Error"
        return $false
    }
}

# --- Static Configuration Deployment ---
function Deploy-StaticConfig {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$StaticConfigContent,
        
        [Parameter(Mandatory = $true)]
        [string]$User,
        
        [Parameter(Mandatory = $true)]
        [string]$SshHost,
        
        [Parameter(Mandatory = $true)]
        [string]$Password,
        
        [Parameter(Mandatory = $false)]
        [int]$Port = 22,
        
        [Parameter(Mandatory = $false)]
        [string]$RemoteConfigPath = "/etc/traefik/traefik.yaml",
        
        [Parameter(Mandatory = $false)]
        [bool]$CreateBackup = $true
    )

    $tempLocalFile = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath "traefik_static_config_$(Get-Random).yaml"

    try {
        # Create backup of existing static config if it exists
        if ($CreateBackup) {
            Write-TraefikLog "Creating backup of existing static configuration..." -Level "Info"
            $backupResult = Backup-StaticConfig -User $User -SshHost $SshHost -Password $Password -Port $Port -RemoteConfigPath $RemoteConfigPath
            if ($backupResult) {
                Write-TraefikLog "Static configuration backed up to: $backupResult" -Level "Success"
            }
        }

        # Save static config content to temporary file
        $StaticConfigContent | Set-Content -Path $tempLocalFile -Encoding UTF8 -ErrorAction Stop
        Write-TraefikLog "Created temporary static config file: $tempLocalFile" -Level "Debug"

        # Create directories if they don't exist
        $configDir = Split-Path $RemoteConfigPath -Parent
        $createDirCommand = "mkdir -p `"$configDir`" && mkdir -p /etc/traefik/ssl && mkdir -p /var/log/traefik"
        $dirResult = Invoke-SSHCommand -User $User -SshHost $SshHost -Password $Password -Port $Port -Command $createDirCommand
        
        if (-not $dirResult.Success) {
            Write-TraefikLog "Warning: Could not create directories: $($dirResult.Stderr)" -Level "Warning"
        }

        # Upload static configuration
        $uploadSuccess = Invoke-FileUpload -LocalPath $tempLocalFile -RemotePath $RemoteConfigPath -User $User -SshHost $SshHost -Password $Password -Port $Port

        if ($uploadSuccess) {
            # Set proper permissions
            $chmodCommand = "chmod 644 `"$RemoteConfigPath`" && chown root:root `"$RemoteConfigPath`""
            $chmodResult = Invoke-SSHCommand -User $User -SshHost $SshHost -Password $Password -Port $Port -Command $chmodCommand
            
            Write-TraefikLog "Successfully deployed static configuration to: $RemoteConfigPath" -Level "Success"
            return $true
        }
        else {
            Write-TraefikLog "Failed to deploy static configuration" -Level "Error"
            return $false
        }
    }
    catch {
        Write-TraefikLog "Error during static configuration deployment: $($_.Exception.Message)" -Level "Error"
        return $false
    }
    finally {
        # Cleanup temporary file
        if (Test-Path $tempLocalFile) {
            Remove-Item $tempLocalFile -Force -ErrorAction SilentlyContinue
            Write-TraefikLog "Cleaned up temporary file: $tempLocalFile" -Level "Debug"
        }
    }
}

# --- Static Configuration Management ---
function Get-StaticConfigContent {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$User,
        
        [Parameter(Mandatory = $true)]
        [string]$SshHost,
        
        [Parameter(Mandatory = $true)]
        [string]$Password,
        
        [Parameter(Mandatory = $false)]
        [int]$Port = 22,
        
        [Parameter(Mandatory = $false)]
        [string]$RemoteConfigPath = "/etc/traefik/traefik.yaml"
    )

    try {
        $command = "cat `"$RemoteConfigPath`" 2>/dev/null || echo 'FILE_NOT_FOUND'"
        $result = Invoke-SSHCommand -User $User -SshHost $SshHost -Password $Password -Port $Port -Command $command

        if ($result.Success -and $result.Stdout -ne "FILE_NOT_FOUND") {
            Write-TraefikLog "Successfully retrieved static configuration" -Level "Success"
            return $result.Stdout
        }
        else {
            Write-TraefikLog "Static configuration file not found or not accessible" -Level "Warning"
            return $null
        }
    }
    catch {
        Write-TraefikLog "Error retrieving static configuration: $($_.Exception.Message)" -Level "Error"
        return $null
    }
}

function Edit-StaticConfig {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$User,
        
        [Parameter(Mandatory = $true)]
        [string]$SshHost,
        
        [Parameter(Mandatory = $true)]
        [string]$Password,
        
        [Parameter(Mandatory = $false)]
        [int]$Port = 22,
        
        [Parameter(Mandatory = $false)]
        [string]$Editor = "notepad.exe",
        
        [Parameter(Mandatory = $false)]
        [string]$RemoteConfigPath = "/etc/traefik/traefik.yaml"
    )

    $tempLocalFile = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath "edit_static_config_$(Get-Random).yaml"

    try {
        # Download current static configuration
        Write-TraefikLog "Downloading static configuration for editing" -Level "Info"
        
        $downloadSuccess = Invoke-FileDownload -RemotePath $RemoteConfigPath -LocalPath $tempLocalFile -User $User -SshHost $SshHost -Password $Password -Port $Port
        
        if (-not $downloadSuccess) {
            Write-TraefikLog "Failed to download static configuration for editing" -Level "Error"
            return $false
        }

        # Get original content for comparison and backup
        $originalContent = Get-Content -Path $tempLocalFile -Raw -ErrorAction SilentlyContinue

        # Create backup before editing
        if ($originalContent) {
            Save-StaticConfigBackup -Content $originalContent -BackupSuffix "pre_edit"
        }

        # Open in editor
        Write-TraefikLog "Opening static configuration in editor: $Editor" -Level "Info"
        Write-Host "Opening static configuration in $Editor..." -ForegroundColor Cyan
        Write-Host "⚠️  Warning: Changing entry point or certificate resolver names will require updating existing services!" -ForegroundColor Yellow
        Write-Host "Please save and close the editor when finished." -ForegroundColor Yellow
        
        $editorProcess = Start-Process -FilePath $Editor -ArgumentList "`"$tempLocalFile`"" -Wait -PassThru
        $editorProcess.WaitForExit()

        # Check if file was modified
        $newContent = Get-Content -Path $tempLocalFile -Raw -ErrorAction SilentlyContinue
        if ($newContent -eq $originalContent) {
            Write-Host "No changes detected. Upload cancelled." -ForegroundColor Yellow
            Write-TraefikLog "No changes made to static configuration" -Level "Info"
            return $true
        }

        # Confirm upload
        Write-Host "`n⚠️  Important: After uploading, you may need to restart Traefik for changes to take effect." -ForegroundColor Yellow
        $confirm = Read-Host "Upload modified static configuration? (y/N)"
        if ($confirm -eq 'y' -or $confirm -eq 'Y') {
            Write-Host "Uploading static configuration..." -ForegroundColor Cyan
            
            $uploadSuccess = Invoke-FileUpload -LocalPath $tempLocalFile -RemotePath $RemoteConfigPath -User $User -SshHost $SshHost -Password $Password -Port $Port
            
            if ($uploadSuccess) {
                Write-TraefikLog "Successfully updated static configuration" -Level "Success"
                Write-Host "Static configuration updated successfully!" -ForegroundColor Green
                Write-Host "Remember to restart Traefik: sudo systemctl restart traefik" -ForegroundColor Green
                
                # Suggest configuration sync check
                Write-Host "`n💡 Tip: Use 'Test Configuration Compatibility' to check if existing services need updates." -ForegroundColor Cyan
                return $true
            }
            else {
                Write-TraefikLog "Failed to upload modified static configuration" -Level "Error"
                Write-Host "Failed to upload static configuration!" -ForegroundColor Red
                return $false
            }
        }
        else {
            Write-TraefikLog "User cancelled static config upload" -Level "Info"
            Write-Host "Upload cancelled." -ForegroundColor Yellow
            return $true
        }
    }
    catch {
        Write-TraefikLog "Error during static config edit operation: $($_.Exception.Message)" -Level "Error"
        Write-Host "Error during edit operation: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
    finally {
        # Cleanup temporary file
        if (Test-Path $tempLocalFile) {
            Remove-Item $tempLocalFile -Force -ErrorAction SilentlyContinue
            Write-TraefikLog "Cleaned up temporary edit file: $tempLocalFile" -Level "Debug"
        }
    }
}

function Backup-StaticConfig {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$User,
        
        [Parameter(Mandatory = $true)]
        [string]$SshHost,
        
        [Parameter(Mandatory = $true)]
        [string]$Password,
        
        [Parameter(Mandatory = $false)]
        [int]$Port = 22,
        
        [Parameter(Mandatory = $false)]
        [string]$RemoteConfigPath = "/etc/traefik/traefik.yaml",
        
        [Parameter(Mandatory = $false)]
        [string]$BackupSuffix = ""
    )

    try {
        # Get current static config content
        $content = Get-StaticConfigContent -User $User -SshHost $SshHost -Password $Password -Port $Port -RemoteConfigPath $RemoteConfigPath
        
        if ($content) {
            return Save-StaticConfigBackup -Content $content -BackupSuffix $BackupSuffix
        }
        else {
            Write-TraefikLog "No static configuration found to backup" -Level "Warning"
            return $null
        }
    }
    catch {
        Write-TraefikLog "Error creating static config backup: $($_.Exception.Message)" -Level "Error"
        return $null
    }
}

function Save-StaticConfigBackup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Content,
        
        [Parameter(Mandatory = $false)]
        [string]$BackupSuffix = ""
    )

    try {
        $backupDir = Join-Path (Get-Location) "backups"
        if (-not (Test-Path $backupDir)) {
            New-Item -ItemType Directory -Path $backupDir -Force | Out-Null
            Write-TraefikLog "Created backup directory: $backupDir" -Level "Info"
        }

        $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
        $backupFileName = if ($BackupSuffix) {
            "static_config_$BackupSuffix`_$timestamp.yaml"
        } else {
            "static_config_$timestamp.yaml"
        }
        $backupFile = Join-Path $backupDir $backupFileName

        $Content | Set-Content -Path $backupFile -Encoding UTF8 -ErrorAction Stop
        Write-TraefikLog "Created static config backup: $backupFile" -Level "Success"
        return $backupFile
    }
    catch {
        Write-TraefikLog "Failed to create static config backup: $($_.Exception.Message)" -Level "Warning"
        return $null
    }
}

# Export functions
Export-ModuleMember -Function @(
    'New-TraefikStaticYaml',
    'Test-DNSCredentials',
    'Deploy-StaticConfig',
    'Get-StaticConfigContent',
    'Edit-StaticConfig',
    'Backup-StaticConfig',
    'Save-StaticConfigBackup'
)